# Use root/example as user/password credentials
# docker pull mongo
version: "2"

services:
  mongo:
    image: mongo
    container_name: mosh-mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    ports:
      - "27017:27017"
    volumes:
      - /home/ion/docker/mongo/data/db:/data/db
      - /home/ion/docker/mongo/data/configdb:/data/configdb
